name: Secret Demo
on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar uso da Secret
        env:
          MY_KEY: ${{ secrets.API_KEY }}
        run: echo "API_KEY configurado (valor oculto pelo GitHub)"